<a href="https://colab.research.google.com/github/inefable12/CQCPE_2023_jesus/blob/main/Ejercicios_de_repado_G8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. Crea una lista de 10 números e imprime los valores negativos en otra lista

In [5]:
type([1,2,3,4])

list

In [20]:
mi_lista = [1,2,3,4,1,2,3,4,1,100]

In [21]:
2*mi_lista

[1, 2, 3, 4, 1, 2, 3, 4, 1, 100, 1, 2, 3, 4, 1, 2, 3, 4, 1, 100]

In [7]:
import numpy as np

In [15]:
mis_numeros = np.random.randint(1,20,size=10)

In [13]:
len(mis_numeros)

10

In [16]:
mis_numeros

array([13,  7, 15, 13, 12, 13,  6, 11, 13, 11])

In [17]:
2*mis_numeros

array([26, 14, 30, 26, 24, 26, 12, 22, 26, 22])

In [24]:
# [lo que quiero | como lo voy a generar]

[x*-1 for x in mi_lista]

[-1, -2, -3, -4, -1, -2, -3, -4, -1, -100]

# 2. Escribe una matriz de 3x3 con números float distintos

In [34]:
numeros = [[2.0,8.11,3.3],
           [3.4,2.55,9.1],
           [1.2,8.30,0.5]]

In [28]:
type([[2.0,8.11,3.3],[3,2,9],[1,8,0]])

list

In [35]:
numeros[2][1]

8.3

In [36]:
np.random.random_sample((3,3))

array([[0.4394605 , 0.80813932, 0.19129644],
       [0.49189843, 0.48940562, 0.58136422],
       [0.94484526, 0.90192317, 0.62521032]])

# 3. Crea una matriz A de 3x3 y 2 matrices (B y C) de 3x1 con números enteros distintos y calcula AxB+C

In [37]:
A = np.random.random_sample((3,3))
B = np.random.random_sample((3,1))
C = np.random.random_sample((3,1))

In [41]:
A.shape, B.shape, C.shape

((3, 3), (3, 1), (3, 1))

In [50]:
# La siguiente no es una operación entre matrices
A*B+C

array([[0.86878739, 1.01255075, 0.62261365],
       [1.03867444, 1.26893296, 1.34731037],
       [0.69991729, 0.81073851, 0.70418348]])

In [51]:
A@B+C

array([[2.22482553],
       [2.13261678],
       [2.10091143]])

In [52]:
np.dot(A,B)+C

array([[2.22482553],
       [2.13261678],
       [2.10091143]])

In [45]:
B

array([[0.85177757],
       [0.98457728],
       [0.84116951]])

In [46]:
C

array([[0.20025516],
       [0.68972772],
       [0.11954312]])

# 4. Disponer de números enteros desde el 1 hasta el 100 y cambiar los múltiplos de 3 por el string “m3”

# 5. Recorriendo la matriz A del ejercicio 3, calcular la traza de la matriz transpuesta

# 6. Encuentra un autovalor y su autovector, para la matriz D. Puedes ayudarte multiplicando D con las matrices de 2x1 E, F y G

Si:

D = np.array([[3, 2], [1, 4]])

E = np.array([[1,0]])

F = np.array([[0,1]])

G = np.array([[1,1]])